[build]
publish = "public"
command = "git submodule update --init --recursive && hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.111.3"
HUGO_ENABLEGITINFO = "true"

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "git submodule update --init --recursive && hugo --gc --minify --baseURL $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "git submodule update --init --recursive && hugo --gc --minify --baseURL $DEPLOY_PRIME_URL"

[[redirects]]
from = "/categories/project-management/*"
to = "/tags/project-management/:splat"
status = 301

[[redirects]]
from = "/categories/time-tracking/*"
to = "/tags/time-tracking/:splat"
status = 301

[[redirects]]
from = "/categories/invoicing/*"
to = "/tags/invoicing/:splat"
status = 301

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
